name: Basic CI docker worker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker container
        run: |
          docker build -t ci-docker .

      - name: Run docker container
        run: |
          docker run ci-docker