name: Basic CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install CMake
        run: |
          mkdir -p /home/runner/cmake-3.31.0
          cd /home/runner/cmake-3.31.0
          wget https://cmake.org/files/v3.31/cmake-3.31.0-linux-x86_64.sh
          echo "y" | sh cmake-3.31.0-linux-x86_64.sh --prefix=/home/runner/cmake-3.31.0 --exclude-subdir
          sudo update-alternatives --install /usr/bin/cmake cmake /home/runner/cmake-3.31.0/bin/cmake 60

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y curl fish wget git gdb ninja-build libboost-all-dev libssl-dev

      - name: Verify installations
        run: |
          cmake --version
          ninja --version
          gdb --version

      - name: Build and test your project
        run: |
          # Add commands to build and test your project
          echo "Build and test steps go here"